### ISSUE TITLE
Encryption Manager returning invalid keys for Face Id while authentication

### ISSUE THREAD

**Issue by niteshsirohi1** [okta/okta-oidc-android#327] opened 2022-06-23 09:30 UTC
### Describe the bug?

When we run your sample and enable smart lock with Face id, after restart your sample it will ask for smart lock and while providing face id, it returns invalid keys and logging out the user.

### What is expected to happen?

It will allow user to login with face id

### What is the actual behavior?

It is returning invalid keys.
 mSmartLockHelper.showSmartLockChooseDialog(this, new SmartLockHelper.FingerprintCallback(this, encryptionManager) {
                        @Override
                        protected void onSuccess() {
                            if (encryptionManager.isValidKeys()) {
                                showUserInfo();
                            } else {
                                // IN CASE OF FACE ID THIS BLOCK CALLED AFTER FACE DETECTION
                                clearStorage();
                            }
                        }

### Reproduction Steps?

Steps to reproduce:-
1. Enable smart lock with Face ID
2. kill app and restart again
3. Biometric prompt comes
4. select Finger Print to authenticate 
5. It will accept Face ID and we got invalid Keys

### SDK Version

'com.okta.android:okta-oidc-android:1.2.2'  this version for OKTA
'androidx.biometric:biometric:1.1.0-beta01'  this version for biomatric

**Comment by JayNewstrom** [comment] 2022-06-23 14:55
This is a duplicate of https://github.com/okta/samples-android/issues/80

**Closed by JayNewstrom** 2022-06-23 14:55 UTC
Labels: bug
