### ISSUE TITLE
WebClient not opening when running with lifecycle runtime 2.3.0

### ISSUE THREAD

**Issue by mchemin** [okta/okta-oidc-android#228] opened 2021-03-30 14:32 UTC
**Repro step**

1. Create a project with dependency on `"androidx.lifecycle:lifecycle-runtime-ktx:2.3.0"`
2. Call `WebAuthClient#singnIn`

**Expected result**
The web client open with the correct login page

**Actual result**
Okta SDK fails silently and the login page does not opened.

**Suggested explanation**
We have observed that the call `OktaResultFragment fragment = new OktaResultFragment();` in `OktaResultFragment` is done inside the `RequestDispatcher mDispatcher` from the `WebAuthClientImpl` class.
The code from the `RequestDispatcher` shows us that the instantiation of the fragment is done using a background thread executor.

The `"androidx.lifecycle:lifecycle-runtime-ktx:2.3.0"` now forces fragment to be created on the main thread see the [release note](https://developer.android.com/jetpack/androidx/releases/lifecycle#2.3.0-alpha06)

_Edit put the correct dependencies_

**Comment by JayNewstrom** [comment] 2021-03-30 14:54
Hi @mchemin sorry to hear you're having an issue with the SDK.

I tried to reproduce this in one of our internal apps (Adding `"androidx.lifecycle:lifecycle-livedata-ktx:2.3.0"`), but I wasn't able to recreate the issue. Do you have more information, or a reproduction sample for us to debug?

**Comment by mchemin** [comment] 2021-03-30 15:00
I'm sorry it was with `androidx.lifecycle:lifecycle-runtime-ktx:2.3.0`
I'll try to make a sample before tomorrow.

**Comment by JayNewstrom** [comment] 2021-03-30 15:24
Thanks for the update! I'm able to reproduce now.

I've created an internal issue for us to fix this: OKTA-383062

As a temporary workaround, I'd suggest not updating for now.

**Comment by mchemin** [comment] 2021-03-30 15:31
Thanks for your quick answer !

**Comment by NikitaAvraimov-okta** [comment] 2021-04-05 14:04
@mchemin Fix is merged into master, we`ll notify once it`s published

**Comment by EtienneStPierre** [comment] 2021-04-12 13:29
> @mchemin Fix is merged into master, we will notify once it`s published

Hi, I was wondering if you have an ETA for the release of version 1.0.8

Thank you!

**Comment by NikitaAvraimov-okta** [comment] 2021-04-21 14:20
@EtienneStPierre It`s on our shortlist, we will post an update here when it`s released

**Comment by claire-1** [comment] 2021-05-25 19:43
Hello, are there any updates on when this fix will be released? 

I would like to update to the latest version of [react-native-keychain](https://github.com/oblador/react-native-keychain) (v 7.0.0), but it adds a dependency on [androidx.lifecycle:lifecycle-viewmodel:2.3.1](https://github.com/oblador/react-native-keychain/blob/master/android/build.gradle#L62), which breaks the Okta experience on my app for the reasons already described in this thread. It would be great if this could be fixed so I can upgrade.

**Comment by JayNewstrom** [comment] 2021-06-22 14:14
I apologize for the delay.
This has been released as https://github.com/okta/okta-oidc-android/releases/tag/1.0.19
Please note the change in maven coordinates.

**Closed by JayNewstrom** 2021-06-22 14:14 UTC
