### ISSUE TITLE
Slow performance of SessionClient.isAuthenticated()

### ISSUE THREAD

**Issue by zirman** [okta/okta-oidc-android#251] opened 2021-07-13 14:53 UTC
Calling SessionClient.isAuthenticated() takes over 800ms if app is "force stop" and restarted. Logging out and back in with a new session fixes the issue.

**Comment by zirman** [comment] 2021-07-13 14:58
Also, calling refreshToken() fixes the slow performance.

**Comment by JayNewstrom** [comment] 2021-07-13 17:18
Hi, thanks for reporting this issue. I'll see if I can reproduce it.

**Comment by JayNewstrom** [comment] 2021-07-13 18:49
This sounds like it's similar to https://github.com/okta/okta-oidc-android/issues/226

I have a few guesses here:
- The android runtime likely (slightly) optimizes code after it's first run
- Some of the things we're using are cached after first use (ie, shared preferences, our default storage engine)
- We're doing 2 types of work that typically take a while (disk access, cryptography)

Unfortunately I don't see an obvious path forward, or an obvious bug. However, I am able to recreate what you're seeing (the SDK is slow during the first invocation of the SDK).

My purposed next steps would be for us to create a larger effort internally, and strive to an overall optimization (since this seems to affect all/most SDK methods.

I've created an internal task for this: OKTA-411630

**Comment by zirman** [comment] 2021-07-14 17:33
In my application, subsequent runs don't improve performance. Still getting 800ms. Refreshing tokens does improve prove the performance as a work around.

**Comment by JayNewstrom** [comment] 2021-07-14 18:21
I'm not able to reproduce continual slowness. Have you tried this on multiple devices? Which devices are you experiencing this on? Are you able to reproduce this on any of our samples?

**Comment by zirman** [comment] 2021-07-14 18:24
I'm on a Pixel 4a. I have a work around in place and I'm on a tight deadline to get this project out at the end of the month. After that I can delve more deeply after launch.

**Comment by JayNewstrom** [comment] 2021-07-14 18:43
Are you able to use another sdk method to check the current status? I'm not sure what you're trying to do, and would need more info to provide more concrete guidance, but something like `mSessionClient.getTokens().isAccessTokenExpired()` might do the trick and be much faster.

**Comment by zirman** [comment] 2021-07-14 18:51
When going to a new screen, I check if the user is authenticated to start the login flow if required. I haven't tried .isAccessTokenExpired(). Does that also return false if the user is not authenticated?

**Comment by JayNewstrom** [comment] 2021-07-14 19:50
`mSessionClient.getTokens()` will return null unless the user has been signed in.

**Comment by JayNewstrom** [comment] 2022-05-26 23:00
Given we're not able to reproduce, I'm going to close this.

**Closed by JayNewstrom** 2022-05-26 23:00 UTC
