### ISSUE TITLE
Authorization Exception - Keys are invalid null

### ISSUE THREAD

**Issue by mdeveracoding** [okta/okta-oidc-android#90] opened 2019-08-28 05:53 UTC
All,

I can successfully log in without any issues.  But after logging in for a second time I get a new session token but immediately get the authorization exception error below.  What is type 4 and code 5003 mean?  Or what do I have to do to successfully log in the second time?  FYI...the error does occur on a PIXEL 3PXL with Android 9.  But other phones such as a Galaxy 8 with a different Android version does not produce an authorization error after a second login attempt.

    AuthorizationException: {"type":4,"code":5003,"error":"Keys are invalid. null"} 

    Code snippet that produces the AuthorizationException....

try {

            _config = OIDCConfig.Builder().clientId(oktaConfigSetting.clientId!!)
                    .redirectUri(oktaConfigSetting.redirectUrl!!).endSessionRedirectUri(oktaConfigSetting.redirectUrl!!)
                    .discoveryUri(oktaConfigSetting.issuer!!).scopes(oktaConfigSetting.scopes!!)
                    .create()

            _authClient = Okta.AuthBuilder().withConfig(_config!!).withContext(_context)
                    .withStorage(SharedPreferenceStorage(_context)).create()

            _sessionClient = _authClient!!.sessionClient

            _authClient?.signIn(_sessionToken, null, object : RequestCallback<Result, AuthorizationException> {

                override fun onSuccess(result: Result) {

                    val tokens = _sessionClient!!.tokens
                    _accessToken = tokens.accessToken
                    _refreshToken = tokens.refreshToken
                    map.putString("accessToken", _accessToken)
                    map.putString("refreshToken", _refreshToken)
                    promise.resolve(map)
                    Log.d(_SUCCESSLOGIN, tokens.toString())

                }

                override fun onError(error: String, exception: AuthorizationException) {

                    val temp = error
                    val e = exception
                    promise.reject(_ERROR, "Could not get an access or refresh token.")
                    Log.d(_ERROR, exception.toString())

                }

            })

**Comment by FeiChen-okta** [comment] 2019-08-29 00:29
@mdeveracoding I can reproduce the issue and working on a fix. It is a problem with decryption The current encryption implementation is using RSA chunking and it looks like that device doesn't like it. In the mean time you can disable encryption by mocking the EncryptionManager and set it when initializing the OIDC config. 

For reference:
https://github.com/okta/okta-oidc-android/blob/master/library/src/test/java/com/okta/oidc/util/EncryptionManagerStub.java

**Comment by mdeveracoding** [comment] 2019-08-29 13:26
@FeiChen-okta Thank you so much for quickly responding!  Is there an ETA to fix the issue that I'm reporting?

**Comment by FeiChen-okta** [comment] 2019-08-29 20:57
@mdeveracoding As soon as I have a fix and tested on a number of real devices. Probably early next week.

**Comment by FeiChen-okta** [comment] 2019-08-31 00:39
@mdeveracoding 1.0.3 is released which should fix the issue with PIXEL3. One note is that the encryption manager initialization is slow due to the strong box initialization. Will look into it for future improvements.

**Comment by mdeveracoding** [comment] 2019-09-04 12:54
@FeiChen-okta ....thank you!

**Comment by FeiChen-okta** [comment] 2019-09-25 00:11
Fixed in 1.0.3 release

**Closed by FeiChen-okta** 2019-09-25 00:11 UTC
