### ISSUE TITLE
sso sample app

### ISSUE THREAD

**Issue by kshiv06** [okta/okta-oidc-android#217] opened 2021-02-09 23:29 UTC
Do you have a sample app that shows Single Sign-On behavior using Custom UI on Native android apps?

**Comment by JayNewstrom** [comment] 2021-02-10 03:01
Hi 👋 Thanks for reaching out!

It looks like this might be a duplicate of https://github.com/okta/okta-oidc-android/issues/188 (if not, likely close).

Could you please elaborate on your use case for us? Thanks!

**Comment by kshiv06** [comment] 2021-02-10 03:16
This link talks about support for sso between mobile and web. In our case, we have multiple flavors/multiple apps in our organization and we are using custom UI without browser. So for example, the user installs one app on their Android device and signs in, is there an option to sign in the user automatically when they install a second app by storing the refreshToken and other tokens that were obtained while authenticating the user on the first app.

**Comment by NikitaAvraimov-okta** [comment] 2021-02-10 08:16
It theory it is possible to share token data between apps, for example via a contentProvider, but it is not a behavior we have checked previously, we will check if it is possible without any modifications to library sc.

**Comment by JayNewstrom** [comment] 2021-02-10 15:16
Thanks for clarifying your use case. We've got an internal ticket (internal ref: OKTA-233991)

For this use case, but it's low on our priority list right now.

It's important to consider the security requirements around this use case.
If you choose to go down the content provider route, make sure you protect it from apps outside of your organization. Here's an example of how one might go about doing that. http://blog.sqisland.com/2011/11/android-protect-contentprovider-with.html

**Comment by kshiv06** [comment] 2021-02-10 17:25
thanks for your response. If we decide to go with the contentprovider, what tokens can we save to retrieve the sessionClient? Our specific use case is- when we install the second app, we need to get a new accesstoken using the session client and refresh token obtained in the previous login from the first app. Is this even possible?

**Comment by JayNewstrom** [comment] 2021-02-10 17:34
It's definitely possible! But the architecture used is going to be highly dependent on your use case. Feel free to reach out to our support team https://support.okta.com/ for help with your specific use case.

**Closed** 2021-02-24 20:08 UTC
