### ISSUE TITLE
Pixel 3 - 1.0.4 - Error: Unable to decrypt ProviderConfiguration the key used may be invalidated. Please clear data and try again. null

### ISSUE THREAD

**Issue by aminner** [okta/okta-oidc-android#113] opened 2019-10-23 18:54 UTC
We are currently running into the following on Pixel 3s:

`Unable to decrypt ProviderConfiguration the key used may be invalidated. Please clear data and try again. null `

If the user clears the app cache and data, it's fine for a single use and then the same thing occurs. 

Any suggestions/workarounds?

**Comment by FeiChen-okta** [comment] 2019-10-23 19:00
Hi @aminner can you send a log of the exception and the when are you running into this issue?
For example does it work on initial login but then fails when exiting out of the app and returning?
Also the pixel3s device properties such as OS version etc.

**Comment by aminner** [comment] 2019-10-23 19:04
Hi @FeiChen-okta,

We do not have a physical device to test this on unfortunatly and were using a coworkers phone as we put our application into a pilot. I'm going to see if I can get a log quick.

The initial log-in is successful, any subsequent log in is failing. We are experiencing this with both an 

Pixel 3 and Pixel 3XL on Android 10, BuildNumber QP1A191005.007

**Comment by aminner** [comment] 2019-10-23 19:15
See error from the logs below: 

`2019-10-23 15:14:44.056 8665-8665/ E/AndroidRuntime: FATAL EXCEPTION: main
    Process: , PID: 8665
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: AuthorizationException: {"type":4,"code":5006,"error":"Illegal block size. Unable to decrypt TokenResponse the key used may be invalidated. Please clear data and try again. null","errorDescription":"Unable to decrypt TokenResponse the key used may be invalidated. Please clear data and try again. null"}
        at com.okta.oidc.util.AuthorizationException$EncryptionErrors.byEncryptionException(AuthorizationException.java:520)
        at com.okta.oidc.clients.sessions.SyncSessionClientImpl.getTokens(SyncSessionClientImpl.java:207)
        at com.okta.oidc.clients.sessions.SessionClientImpl.getTokens(SessionClientImpl.java:108)
        at org.members1st.authorization.services.IdaasAuthorizationService$authenticateViaOktaAndroidSDK$1.onSuccess(IdaasAuthorizationService.kt:112)
        at org.members1st.authorization.services.IdaasAuthorizationService$authenticateViaOktaAndroidSDK$1.onSuccess(IdaasAuthorizationService.kt:110)
        at com.okta.oidc.clients.AuthClientImpl.lambda$null$0(AuthClientImpl.java:73)
        at com.okta.oidc.clients.-$$Lambda$AuthClientImpl$YLKA2acDbflJH_fn8bDVG4-_xeA.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) `

**Comment by FeiChen-okta** [comment] 2019-10-23 19:33
Looks like this is a similar issue that was fixed. The problem was due to strong box encryption on PIXEL3 Android 9. It looks like Android 10 introduced some changes that caused decryption failure. I'll have to get a PIXEL3 and update to Android 10 to reproduce the issue. For reference https://github.com/okta/okta-oidc-android/pull/92

**Comment by aminner** [comment] 2019-10-24 00:13
Thank you for looking into it! 

Is there anything we can do as a workaround until this is fixed?

**Comment by FeiChen-okta** [comment] 2019-10-24 00:27
@aminner Yes you can disable the default encryption and replace it with your own like the following:
https://github.com/okta/okta-oidc-android#Encryption-and-decryption-errors
In point number 4. It have a sample on using EncryptedSharedPreferences which uses AES. That should work with more devices than the default one, which uses RSA. Or you can implement your own.

The links to the example files in the README are broken due to wrong branch it should be:

https://github.com/okta/okta-oidc-android/blob/master/app/src/main/java/com/okta/oidc/example/NoEncryption.java

https://github.com/okta/okta-oidc-android/blob/master/app/src/main/java/com/okta/oidc/example/EncryptedSharedPreferenceStorage.java

**Comment by aminner** [comment] 2019-10-28 19:28
We were able to check that this is NOT an issue with the Pixel 4 today, just figured I'd pass that along, it seems to be fully isolated to the Pixel 3.

**Comment by FeiChen-okta** [comment] 2019-10-31 17:36
@aminner I'm having a hard time reproducing the issue. I'm using a PIXEL 3 XL with the following build info:
[ro.system.build.version.incremental]: [5869620]
[ro.system.build.version.release]: [10]
[ro.product.build.id]: [QP1A.190711.020.C3]

I've also tried with Android 9 on the same device without any issues. Note if you have existing data and upgraded from Android 9 to 10. Those keys are invalidated which can cause the exception. The only way to recover is to call clearData and have the user sign in again.

**Comment by aminner** [comment] 2019-10-31 18:34
Hello! 

When clearing data it will sign-in successfully the first time, but any subsequent logins would fail with the aforementioned error message until you clear the data again. We are also seeming to get this issues with the Samsung S10+, but I'm trying to collect more data on that. 

I'm not sure if the build differences are due to the carrier or purchaser. The individuals having issues were direct buys from google. I know carriers like to add their own flavor to things if they get a chance.

I will see if I can collect some more logs to send you.

**Comment by FeiChen-okta** [comment] 2019-10-31 21:28
@aminner I've published a new release that disables TEE(Trusted execution environment). When using TEE, decryption performance is slow. So we've decided to disable it for now. We'll revisit it in the future.
https://github.com/okta/okta-oidc-android/releases/tag/1.0.5

**Comment by aminner** [comment] 2019-11-01 14:02
@FeiChen-okta  It does seem to have resolved our issue! Thank you so much!

**Comment by FeiChen-okta** [comment] 2019-11-07 21:23
Fixed in 1.0.5 release

**Closed by FeiChen-okta** 2019-11-07 21:23 UTC
