### ISSUE TITLE
Can i use without androidx?

### ISSUE THREAD

**Issue by tackanoway35** [okta/okta-oidc-android#209] opened 2020-12-07 06:51 UTC
My project can't use androidx because some our lib can't update.
How can i use okta-oidc-android without androidx?
Thanks

**Comment by JayNewstrom** [comment] 2020-12-07 16:08
Thanks for the question. It looks like this is a duplicate of #208. Let's try to resolve this issue there!

**Closed by JayNewstrom** 2020-12-07 16:08 UTC
